package com.jobengine.producer.entity;

import com.jobengine.common.dto.JobStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.UUID;

@Entity
@Table(name = "jobs")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Job {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID) // UUID generated by the application, not the DB
    private UUID id;

    @Enumerated(EnumType.STRING) // stores "QUEUED" in the DB, not ordinal (0, 1, 2...)
    @Column(nullable = false)
    private JobStatus status;

    @Column(nullable = false)
    private String type;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb") // stored as binary JSON in PostgreSQL — indexable, queryable
    private Map<String, Object> payload;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist // runs automatically before INSERT
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate // runs automatically before UPDATE
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }
}
